openapi: 3.1.0
info:
  title: Message Publisher API
  version: 1.0.0
servers:
  - url: "http://localhost:8090/"
paths:
  /addMessage:
    post:
      summary: Add a new message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  description: number of items ordered
                  example: 24
                item:
                  type: string
                  description: Item name
                  example: laptop
                address:
                  type: string
                  example: "Evergreen Avenue;42;8500;Beverly Hills;USA"
      responses:
        '200':
          description: Message added successfully
        '400':
          description: Invalid request payload
        '500':
          description: Internal server error